POST http://localhost:5000/api/url/shorten

Content-Type: application/json

{
    "longUrl":"https://www.flipkart.com/envy-women-eau-de-parfum-60-ml/p/itmf3wgyugud52w9?pid=PEREHGFBAUGSPZEF&lid=LSTPEREHGFBAUGSPZEFHNNIUN&marketplace=FLIPKART&spotlightTagId=BestsellerId_g9b%2F0yh%2Fjhz&srno=s_1_1&otracker=search&otracker1=search&fm=SEARCH&iid=4f50407d-b51a-4772-8501-8487f5111570.PEREHGFBAUGSPZEF.SEARCH&ppt=sp&ppn=sp&ssid=ov5deotdy80000001585430825958&qH=fa715abb8273d019"
    
}

