
POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
  "longUrl": "https://www.flipkart.com/samsung-frame-138cm-55-inch-ultra-hd-4k-qled-smart-tv/p/itmfga98hdvdhutc?pid=TVSFGA98TEJ65HKB&lid=LSTTVSFGA98TEJ65HKBPKNXIN&marketplace=FLIPKART&srno=s_1_3&otracker=search&otracker1=search&fm=SEARCH&iid=0a0e36c5-785f-4722-bd6a-7576e1c8a9cc.TVSFGA98TEJ65HKB.SEARCH&ppt=sp&ppn=sp&ssid=2qxhsdfqmo0000001585488089156&qH=8371b0556a974ac9"
}